APA = {
    "authors": {"ln_end": ",", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                "seq1": "lf", "seq2": "lf", "two_int": ", & ", "front_int": ", ", "back_int": ", & ",
                "head": "", "tail": "", "bold": False, "italic": False, "end": " "},
    "year": {"head": "(", "tail": ")", "bold": False, "italic": False, "end": ". "},
    "source": {"head": "Retrieved from ", "tail": "", "bold": False, "italic": False, "end": ""},
    "BookPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "lopu",
    },
    "BookInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "ChapterPublished": {
        "chapter_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                    "seq1": "fl", "seq2": "fl", "two_int": " & ", "front_int": ", ", "back_int": ", & ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                       "inner_end": "", "end": " ("},
        "pages": {"shrink": False, "page_int": "–", "head": "pp. ", "tail": ")", "bold": False, "italic": False, "end": ". "},
        "page_addition": {"head": "", "tail": ", ", "bold": False, "italic": False, "end": ""},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "palo",
    },
    "ChapterInPress": {
        "chapter_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                    "seq1": "fl", "seq2": "fl", "two_int": " & ", "front_int": ", ", "back_int": ", & ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                       "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "JournalPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ", "},
        "volume": {"head": "", "tail": "", "bold": False, "italic": True, "end": ""},
        "issue": {"head": "(", "tail": ")", "bold": False, "italic": False, "end": ", ", "required": False, "omitted": False},
        "pages": {"shrink": False, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    },
    "JournalInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "OnLineJournal": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ". "},
    },
    "Website": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
    },
    "Other": {
        "original": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
}


AMJ = {
    "authors": {"ln_end": ",", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                "seq1": "lf", "seq2": "lf", "two_int": ", & ", "front_int": ", ", "back_int": ", & ",
                "head": "", "tail": "", "bold": False, "italic": False, "end": " "},
    "year": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    "source": {"head": "Retrieved from ", "tail": "", "bold": False, "italic": False, "end": ""},
    "BookPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                  "inner_end": "", "end": ". "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "lopu",
    },
    "BookInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                  "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "ChapterPublished": {
        "chapter_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": " ", "n_int": "",
                    "seq1": "fl", "seq2": "fl", "two_int": " & ", "front_int": ", ", "back_int": " & ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                       "inner_end": "", "end": ""},
        "pages": {"shrink": False, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "page_addition": {"head": ", ", "tail": "", "bold": False, "italic": False, "end": ": "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "palo",
    },
    "ChapterInPress": {
        "chapter_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": " ", "n_int": "",
                    "seq1": "fl", "seq2": "fl", "two_int": " & ", "front_int": ", ", "back_int": " & ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                       "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "JournalPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": True, "italic": True, "end": ", "},
        "volume": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
        "issue": {"head": "(", "tail": ")", "bold": False, "italic": False, "end": ": ", "required": False, "omitted": False},
        "pages": {"shrink": False, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    },
    "JournalInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": True, "italic": True, "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "OnLineJournal": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": True, "italic": True, "end": ". "},
    },
    "Website": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                  "inner_end": "", "end": ". "},
    },
    "Other": {
        "original": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
}


AMR = {
    "authors": {"ln_end": ",", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                "seq1": "lf", "seq2": "lf", "two_int": ", & ", "front_int": ", ", "back_int": ", & ",
                "head": "", "tail": "", "bold": False, "italic": False, "end": " "},
    "year": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    "source": {"head": "Retrieved from ", "tail": "", "bold": False, "italic": False, "end": ""},
    "BookPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                  "inner_end": "", "end": ". "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "lopu",
    },
    "BookInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                  "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "ChapterPublished": {
        "chapter_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": " ", "n_int": "",
                    "seq1": "fl", "seq2": "fl", "two_int": " & ", "front_int": ", ", "back_int": " & ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                       "inner_end": "", "end": ""},
        "pages": {"shrink": False, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "page_addition": {"head": ", ", "tail": "", "bold": False, "italic": False, "end": ": "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "palo",
    },
    "ChapterInPress": {
        "chapter_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": " ", "n_int": "",
                    "seq1": "fl", "seq2": "fl", "two_int": " & ", "front_int": ", ", "back_int": " & ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                       "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "JournalPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": True, "italic": True, "end": ", "},
        "volume": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
        "issue": {"head": "(", "tail": ")", "bold": False, "italic": False, "end": ": ", "required": False, "omitted": False},
        "pages": {"shrink": False, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    },
    "JournalInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": True, "italic": True, "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "OnLineJournal": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": True, "italic": True, "end": ". "},
    },
    "Website": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": True, "italic": True,
                  "inner_end": "", "end": ". "},
    },
    "Other": {
        "original": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
}


HR = {
    "authors": {"ln_end": "", "char_end": "", "char_int": "", "fn_end": "", "n_int": " ",
                "seq1": "lf", "seq2": "lf", "two_int": " and ", "front_int": ", ", "back_int": " and ",
                "head": "", "tail": "", "bold": False, "italic": False, "end": " "},
    "year": {"head": "(", "tail": ")", "bold": False, "italic": False, "end": " "},
    "source": {"head": "Available at ", "tail": "", "bold": False, "italic": False, "end": ". "},
    "BookPublished": {
        "title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "lopu",
    },
    "BookInPress": {
        "title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "ChapterPublished": {
        "chapter_title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": "", "char_int": "", "fn_end": "", "n_int": " ",
                    "seq1": "lf", "seq2": "lf", "two_int": ", ", "front_int": ", ", "back_int": ", ",
                    "head": "In: ", "tail": "", "bold": False, "italic": False, "end": " ",
                    "ed1": " (ed)", "ed2": " (eds)"},
        "book_title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": True,
                       "inner_end": "", "end": ". "},
        "pages": {"shrink": False, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "page_addition": {"head": ", ", "tail": "", "bold": False, "italic": False, "end": ", "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
        "seq": "lopa",
    },
    "ChapterInPress": {
        "chapter_title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": "", "char_int": "", "fn_end": "", "n_int": " ",
                    "seq1": "lf", "seq2": "lf", "two_int": ", ", "front_int": ", ", "back_int": ", ",
                    "head": "In: ", "tail": "", "bold": False, "italic": False, "end": " ",
                    "ed1": " (ed)", "ed2": " (eds)"},
        "book_title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": True,
                       "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "JournalPublished": {
        "title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": " "},
        "volume": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
        "issue": {"head": "(", "tail": ")", "bold": False, "italic": False, "end": ": ", "required": True, "omitted": False},
        "pages": {"shrink": False, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    },
    "JournalInPress": {
        "title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ". "},
        "doi": {"head": "Epub ahead of print . DOI: ", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "OnLineJournal": {
        "title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ". "},
    },
    "Website": {
        "title": {"ed_pattern": 2, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
    },
    "Other": {
        "original": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
}


ASQ = {
    "authors": {"ln_end": ",", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                "seq1": "lf", "seq2": "fl", "two_int": ", and ", "front_int": ", ", "back_int": ", and ",
                "head": "", "tail": "", "bold": True, "italic": False, "end": "<br>"},
    "year": {"head": "", "tail": "", "bold": False, "italic": False, "end": " "},
    "source": {"head": "Accessed at ", "tail": "", "bold": False, "italic": False, "end": ". "},
    "BookPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "lopu",
    },
    "BookInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "ChapterPublished": {
        "chapter_title": {"ed_pattern": 1, "head": '“', "tail": '”', "bold": False, "italic": False,
                          "inner_end": ".", "end": " "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                    "seq1": "fl", "seq2": "fl", "two_int": " and ", "front_int": ", ", "back_int": ", and ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (ed.)", "ed2": " (eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                       "inner_end": "", "end": ""},
        "pages": {"shrink": False, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "page_addition": {"head": ", ", "tail": "", "bold": False, "italic": False, "end": ": "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "palo",
    },
    "ChapterInPress": {
        "chapter_title": {"ed_pattern": 1, "head": '“', "tail": '”', "bold": False, "italic": False,
                          "inner_end": ".", "end": " "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                    "seq1": "fl", "seq2": "fl", "two_int": " and ", "front_int": ", ", "back_int": ", and ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (ed.)", "ed2": " (eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                       "inner_end": "", "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "JournalPublished": {
        "title": {"ed_pattern": 1, "head": '“', "tail": '”', "bold": False, "italic": False,
                  "inner_end": ".", "end": " "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": False, "end": ", "},
        "volume": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
        "issue": {"head": "(", "tail": ")", "bold": False, "italic": False, "end": ": ", "required": False, "omitted": False},
        "pages": {"shrink": False, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    },
    "JournalInPress": {
        "title": {"ed_pattern": 1, "head": '“', "tail": '”', "bold": False, "italic": False,
                  "inner_end": ".", "end": " "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "doi": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "OnLineJournal": {
        "title": {"ed_pattern": 1, "head": '“', "tail": '”', "bold": False, "italic": False,
                  "inner_end": ".", "end": " "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    },
    "Website": {
        "title": {"ed_pattern": 1, "head": '“', "tail": '”', "bold": False, "italic": False,
                  "inner_end": ".", "end": " "},
    },
    "Other": {
        "original": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
}


JOM = {
    "authors": {"ln_end": ",", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                "seq1": "lf", "seq2": "lf", "two_int": ", & ", "front_int": ", ", "back_int": ", & ",
                "head": "", "tail": "", "bold": False, "italic": False, "end": " "},
    "year": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    "source": {"head": "Retrieved from ", "tail": "", "bold": False, "italic": False, "end": ""},
    "BookPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "lopu",
    },
    "BookInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
        "doi": {"head": "doi: ", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "ChapterPublished": {
        "chapter_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": " ", "n_int": "",
                    "seq1": "fl", "seq2": "fl", "two_int": " & ", "front_int": ", ", "back_int": ", & ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                       "inner_end": "", "end": ""},
        "pages": {"shrink": False, "page_int": "-", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "page_addition": {"head": ", ", "tail": "", "bold": False, "italic": False, "end": ": "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "palo",
    },
    "ChapterInPress": {
        "chapter_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": "", "char_end": ".", "char_int": " ", "fn_end": " ", "n_int": "",
                    "seq1": "fl", "seq2": "fl", "two_int": " & ", "front_int": ", ", "back_int": ", & ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                       "inner_end": "", "end": ". "},
        "doi": {"head": "doi: ", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "JournalPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ", "},
        "volume": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
        "issue": {"head": "(", "tail": ")", "bold": False, "italic": False, "end": ": ", "required": False, "omitted": False},
        "pages": {"shrink": False, "page_int": "-", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    },
    "JournalInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ". "},
        "doi": {"head": "doi: ", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "OnLineJournal": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ". "},
    },
    "Website": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
    },
    "Other": {
        "original": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
}


JMS = {
    "authors": {"ln_end": ",", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                "seq1": "lf", "seq2": "lf", "two_int": " and ", "front_int": ", ", "back_int": " and ",
                "head": "", "tail": "", "bold": False, "italic": False, "end": " "},
    "year": {"head": "(", "tail": ")", "bold": False, "italic": False, "end": ". "},
    "source": {"head": "Available at ", "tail": "", "bold": False, "italic": False, "end": " (accessed )"},
    "BookPublished": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "seq": "lopu",
    },
    "BookInPress": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
        "doi": {"head": "doi: ", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "ChapterPublished": {
        "chapter_title": {"ed_pattern": 1, "head": "‘", "tail": "’", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": ",", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                    "seq1": "lf", "seq2": "lf", "two_int": " and ", "front_int": ", ", "back_int": " and ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                       "inner_end": "", "end": ". "},
        "pages": {"shrink": True, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
        "page_addition": {"head": "", "tail": ", ", "bold": True, "italic": False, "end": ""},
        "location": {"head": "", "tail": "", "bold": False, "italic": False, "end": ": "},
        "publisher": {"head": "", "tail": "", "bold": False, "italic": False, "end": ", "},
        "seq": "lopa",
    },
    "ChapterInPress": {
        "chapter_title": {"ed_pattern": 1, "head": "‘", "tail": "’", "bold": False, "italic": False,
                          "inner_end": "", "end": ". "},
        "editors": {"ln_end": ",", "char_end": ".", "char_int": " ", "fn_end": "", "n_int": " ",
                    "seq1": "lf", "seq2": "lf", "two_int": " and ", "front_int": ", ", "back_int": " and ",
                    "head": "In ", "tail": "", "bold": False, "italic": False, "end": ", ",
                    "ed1": " (Ed.)", "ed2": " (Eds.)"},
        "book_title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                       "inner_end": "", "end": ". "},
        "doi": {"head": "doi: ", "tail": "", "bold": False, "italic": False, "end": ""},
    },
    "JournalPublished": {
        "title": {"ed_pattern": 1, "head": "‘", "tail": "’", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ", "},
        "volume": {"head": "", "tail": "", "bold": True, "italic": False, "end": ""},
        "issue": {"head": "", "tail": "", "bold": False, "italic": False, "end": ", ", "required": False, "omitted": True},
        "pages": {"shrink": True, "page_int": "–", "head": "", "tail": "", "bold": False, "italic": False, "end": ". "},
    },
    "JournalInPress": {
        "title": {"ed_pattern": 1, "head": "‘", "tail": "’", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ". "},
        "doi": {"head": "doi: ", "tail": "", "bold": False, "italic": False, "end": ". "},
    },
    "OnLineJournal": {
        "title": {"ed_pattern": 1, "head": "‘", "tail": "’", "bold": False, "italic": False,
                  "inner_end": "", "end": ". "},
        "journal": {"head": "", "tail": "", "bold": False, "italic": True, "end": ". "},
    },
    "Website": {
        "title": {"ed_pattern": 1, "head": "", "tail": "", "bold": False, "italic": True,
                  "inner_end": "", "end": ". "},
    },
    "Other": {
        "original": {"head": "", "tail": "", "bold": False, "italic": False, "end": ""},
    },
}
